name: MaintenancePlugin
version: '1.0-SNAPSHOT'
main: org.xianbei235.svPlugin.MaintenancePlugin
authors: [ xianbei235 ]
description: 服务器维护插件
commands:
  sv:
    description: 维护插件指令
    usage: /sv - on/off/add/remove
